### ISSUE TITLE
Faker version

### ISSUE THREAD

**Issue by deizel** [gourmet/faker#2]
Not sure if you noticed when doing aab55e754ec355b8cdf7c6bbdeace86893310a73 but Faker `v1.4.0` is [missing the CakePHP adapters][1]. :umbrella: 

```
PHP Fatal error:  Class 'Faker\ORM\CakePHP\EntityPopulator' not found in /vagrant/vendor/gourmet/faker/src/TestSuite/Fixture/TestFixture.php on line 64
```

[1]: https://github.com/fzaninotto/Faker/tree/v1.4.0/src/Faker/ORM

**Comment by jadb** [comment]
@deizel thanks for pointing it out! I hadn't. I quickly released something close another issue.

This sucks. Could you submit a PR there if you have time? Otherwise I'll do it when I can later this week.

**Comment by deizel** [comment]
> Could you submit a PR there if you have time?  

Looks like there is already one, if this is what you meant: fzaninotto/Faker#463

**Comment by deizel** [comment]
@jadb FYI, Faker 1.5 is out now. ([blog](http://www.redotheweb.com/2015/05/29/faker-15-is-released.html), [release](https://github.com/fzaninotto/Faker/releases/tag/v1.5.0)) :sunny:

**Comment by jadb** [comment]
@deizel - mind checking this out? you asked what I would like help with :stuck_out_tongue_winking_eye:
